import { parseCidr } from 'cidr-tools';
import { stringifyIp } from 'ip-bigint';

import { removeNewlines, iptablesTemplate } from '#server/utils/template';
import { generateAwgParameterLines } from '#server/utils/awgConfig';
import { execFile, withSecureInputFile } from '#server/utils/cmd';
import { WG_ENV } from '#server/utils/config';
import type { ClientType } from '#db/repositories/client/types';
import type { InterfaceType } from '#db/repositories/interface/types';
import type { UserConfigType } from '#db/repositories/userConfig/types';
import type { HooksType } from '#db/repositories/hooks/types';
import type { ConcreteConfigFormat, ConfigFormat } from '#shared/types/runtime';
import { InterfaceNameSchema } from '#shared/utils/schemas';

type Options = {
  enableIpv6?: boolean;
  format?: ConfigFormat;
};

// needed to support cli
const wgExecutable =
  typeof WG_ENV !== 'undefined' ? WG_ENV.WG_EXECUTABLE : 'dev';

export class ConfigFormatUnavailableError extends Error {}

export function resolveClientConfigFormat(
  wgInterface: InterfaceType,
  client: ClientType,
  requested: ConfigFormat = 'auto'
): ConcreteConfigFormat {
  const selected =
    requested === 'auto'
      ? client.preferredConfigFormat === 'auto'
        ? wgInterface.defaultConfigFormat
        : client.preferredConfigFormat
      : requested;

  if (selected === 'migration_pending') {
    throw new ConfigFormatUnavailableError(
      'Interface compatibility migration is unresolved'
    );
  }
  if (selected === 'wireguard' && wgInterface.awgParametersEnabled) {
    throw new ConfigFormatUnavailableError(
      `WireGuard export is unavailable for interface ${wgInterface.name} while AWG parameters are enabled`
    );
  }
  return selected;
}

export const wg = {
  generateServerPeer: (
    client: Omit<ClientType, 'createdAt' | 'updatedAt'>,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const allowedIps = [
      `${client.ipv4Address}/32`,
      ...(enableIpv6 ? [`${client.ipv6Address}/128`] : []),
      ...(client.serverAllowedIps ?? []),
    ];

    const extraLines = [];
    if (client.serverEndpoint) {
      extraLines.push(`Endpoint = ${client.serverEndpoint}`);
    }

    return `# Client: ${client.name} (${client.id})
[Peer]
PublicKey = ${client.publicKey}
PresharedKey = ${client.preSharedKey}
AllowedIPs = ${allowedIps.join(', ')}${extraLines.length ? `\n${extraLines.join('\n')}` : ''}`;
  },

  generateServerInterface: (
    wgInterface: InterfaceType,
    hooks: HooksType,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const cidr4 = parseCidr(wgInterface.ipv4Cidr);
    const cidr6 = parseCidr(wgInterface.ipv6Cidr);
    const ipv4Addr = stringifyIp({ number: cidr4.start + 1n, version: 4 });
    const ipv6Addr = stringifyIp({ number: cidr6.start + 1n, version: 6 });

    const address =
      `${ipv4Addr}/${cidr4.prefix}` +
      (enableIpv6 ? `, ${ipv6Addr}/${cidr6.prefix}` : '');

    const awgLines = generateAwgParameterLines(
      wgInterface.awgParametersEnabled,
      {
        Jc: wgInterface.jC,
        Jmin: wgInterface.jMin,
        Jmax: wgInterface.jMax,
        S1: wgInterface.s1,
        S2: wgInterface.s2,
        S3: wgInterface.s3,
        S4: wgInterface.s4,
        H1: wgInterface.h1,
        H2: wgInterface.h2,
        H3: wgInterface.h3,
        H4: wgInterface.h4,
        I1: wgInterface.i1,
        I2: wgInterface.i2,
        I3: wgInterface.i3,
        I4: wgInterface.i4,
        I5: wgInterface.i5,
      },
      wgExecutable
    );

    const extraLines = [...awgLines].filter((v) => v !== null);

    return `# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${wgInterface.privateKey}
Address = ${address}
ListenPort = ${wgInterface.port}
MTU = ${wgInterface.mtu}
${extraLines.length ? `${extraLines.join('\n')}\n` : ''}
PreUp = ${iptablesTemplate(hooks.preUp, wgInterface)}
PostUp = ${iptablesTemplate(hooks.postUp, wgInterface)}
PreDown = ${iptablesTemplate(hooks.preDown, wgInterface)}
PostDown = ${iptablesTemplate(hooks.postDown, wgInterface)}`;
  },

  generateClientConfig: (
    wgInterface: InterfaceType,
    userConfig: UserConfigType,
    client: ClientType,
    options: Options = {}
  ) => {
    const { enableIpv6 = true, format = 'auto' } = options;
    const resolvedFormat = resolveClientConfigFormat(
      wgInterface,
      client,
      format
    );

    const address =
      `${client.ipv4Address}/32` +
      (enableIpv6 ? `, ${client.ipv6Address}/128` : '');

    const hookLines = [
      client.preUp ? `PreUp = ${removeNewlines(client.preUp)}` : null,
      client.postUp ? `PostUp = ${removeNewlines(client.postUp)}` : null,
      client.preDown ? `PreDown = ${removeNewlines(client.preDown)}` : null,
      client.postDown ? `PostDown = ${removeNewlines(client.postDown)}` : null,
    ];

    const dnsServers = client.dns ?? userConfig.defaultDns;
    const dnsLine =
      dnsServers.length > 0 ? `DNS = ${dnsServers.join(', ')}` : null;

    const awgLines = generateAwgParameterLines(
      resolvedFormat === 'amneziawg' && wgInterface.awgParametersEnabled,
      {
        Jc: client.jC,
        Jmin: client.jMin,
        Jmax: client.jMax,
        S1: wgInterface.s1,
        S2: wgInterface.s2,
        S3: wgInterface.s3,
        S4: wgInterface.s4,
        H1: wgInterface.h1,
        H2: wgInterface.h2,
        H3: wgInterface.h3,
        H4: wgInterface.h4,
        I1: client.i1,
        I2: client.i2,
        I3: client.i3,
        I4: client.i4,
        I5: client.i5,
      },
      wgExecutable
    );

    const extraLines = [dnsLine, ...hookLines, ...awgLines].filter(
      (v) => v !== null
    );

    return `[Interface]
PrivateKey = ${client.privateKey}
Address = ${address}
MTU = ${client.mtu}
${extraLines.length ? `${extraLines.join('\n')}\n` : ''}
[Peer]
PublicKey = ${wgInterface.publicKey}
PresharedKey = ${client.preSharedKey}
AllowedIPs = ${(client.allowedIps ?? userConfig.defaultAllowedIps).join(', ')}
PersistentKeepalive = ${client.persistentKeepalive}
Endpoint = ${userConfig.host}:${userConfig.port}`;
  },

  generatePrivateKey: () => {
    return execFile(wgExecutable, ['genkey']);
  },

  getPublicKey: (privateKey: string) => {
    return execFile(wgExecutable, ['pubkey'], {
      input: `${privateKey}\n`,
      log: `${wgExecutable} pubkey < ***hidden***`,
    });
  },

  generatePreSharedKey: () => {
    return execFile(wgExecutable, ['genpsk']);
  },

  up: (infName: string) => {
    return execFile(`${wgExecutable}-quick`, [
      'up',
      InterfaceNameSchema.parse(infName),
    ]);
  },

  down: (infName: string) => {
    return execFile(`${wgExecutable}-quick`, [
      'down',
      InterfaceNameSchema.parse(infName),
    ]);
  },

  downLegacy: (infName: string) => {
    return execFile('wg-quick', ['down', InterfaceNameSchema.parse(infName)]);
  },

  interfaceExists: async (infName: string) => {
    try {
      await execFile('ip', [
        'link',
        'show',
        'dev',
        InterfaceNameSchema.parse(infName),
      ]);
      return true;
    } catch {
      return false;
    }
  },

  restart: async (infName: string) => {
    const interfaceId = InterfaceNameSchema.parse(infName);
    await execFile(`${wgExecutable}-quick`, ['down', interfaceId]).catch(
      () => {}
    );
    return execFile(`${wgExecutable}-quick`, ['up', interfaceId]);
  },

  sync: async (infName: string) => {
    const interfaceId = InterfaceNameSchema.parse(infName);
    const strippedConfig = await execFile(`${wgExecutable}-quick`, [
      'strip',
      interfaceId,
    ]);
    return withSecureInputFile(`${strippedConfig}\n`, (inputPath) =>
      execFile(wgExecutable, ['syncconf', interfaceId, inputPath])
    );
  },

  validateConfig: async (configPath: string) => {
    await execFile(`${wgExecutable}-quick`, ['strip', configPath], {
      log: `${wgExecutable}-quick strip <generated-config>`,
    });
  },

  dump: async (infName: string) => {
    const rawDump = await execFile(
      wgExecutable,
      ['show', InterfaceNameSchema.parse(infName), 'dump'],
      {
        log: false,
      }
    );

    type wgDumpLine = [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ];

    return rawDump
      .trim()
      .split('\n')
      .slice(1)
      .map((line) => {
        const splitLines = line.split('\t');
        const [
          publicKey,
          preSharedKey,
          endpoint,
          allowedIps,
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = splitLines as wgDumpLine;

        return {
          publicKey,
          preSharedKey,
          endpoint: endpoint === '(none)' ? null : endpoint,
          allowedIps,
          latestHandshakeAt:
            latestHandshakeAt === '0'
              ? null
              : new Date(Number.parseInt(`${latestHandshakeAt}000`)),
          transferRx: Number.parseInt(transferRx),
          transferTx: Number.parseInt(transferTx),
          persistentKeepalive: persistentKeepalive,
        };
      });
  },
};
